    version: '3.8'

    services:
      postgres-db:
        image: postgres:16
        container_name: university-db
        restart: unless-stopped 
        environment:
          POSTGRES_USER: 'admin'
          POSTGRES_PASSWORD: 'password'
          POSTGRES_DB: 'university_data'
        ports:
          - '5432:5432'
        volumes:
          - postgres-data:/var/lib/postgresql/data

    volumes:
      postgres-data:
        
    

